# Run docker-compose build
# Run docker-compose up

## Clean Cached images, containers, volumes and networks
# docker system prune -a

version: '3.5'
services:
  server:
    build: ./server
    container_name: "server"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
    - ./server:/usr/src/app
    env_file:
     - .env
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/usr/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/usr/data/db
    ports:
    - 27017:27017
    command: mongod --logpath=/dev/null

networks:
  default:
    name: server